```{r}

library(tidyverse)
library(readxl)
library(gtsummary)

```

```{r}
S_Data <- read_csv("Data/new file.csv", na = c("", "NA", "N/A", 'n/a', 'no data'))

Data <- S_Data %>%
  transmute(
    ID = `case number`,
    Redo = factor(`re-do`, levels = 0:1, labels = c("No", "Yes")),
    Date_1 = as.POSIXct(`first [date]`, format = "dd/mm/yyyy", tz = "Europe/London"),
    Date_2 = as.POSIXct(`second [date]`, format = "dd/mm/yyyy", tz = "Europe/London"),
    Creatinine_Surgery = as.numeric(`Actual creatinine at time of surgery`),
    Admission_Date = as.POSIXct(`Admission date`, format = "dd-mmm-yy", tz = "Europe/London"),
    Age = as.numeric(`Age at operation`),
    Angina_Status = factor(`Angina status pre-surgery ordinal`, levels = 1:4, labels = c('No Angina', 'Slight limitation of ordinary activity', 'Marked limitation of ordinary activity', 'Symptoms at rest or minimal activity')),
    CABG = factor(CABG, levels = 0:1, labels = c('No', 'Yes')),
    Cardiac_Proc = factor(`Cardiac procedures`, levels = c("CABG + valve", "Valve alone", "Valve + other", "CABG + valve + other")),
    Cardiogenic_Shock = factor(`Cardiogenic shock (pre-operation)`, levels = 0:1, labels = c('No','Ães')),
    Smoking_Stat = factor(`Cigarette smoking history`, labels = c("Current Smoker", "Ex-Smoker", "Never Smoked")),
    Creatinine_Clearance = as.numeric(`Creatinine clearance`),
    DateTime_Op = `Date and time of operation...19`,
    DateTime_LastCardiacOp = `Date of last cardiac operation`,
    DateTime_LastCatheter = `Date of last catheterisation`,
    Diabetes_Mx = factor(`Diabetes management`, labels = c("Not diabetic", "Insulin", "Diet", "Oral therapy")),
    Dyspnoea_Status = factor(`Dyspnoea status pre-surgery`),
    LVEF_Cat = factor(`Ejection fraction category ordinal`, levels = 1:4, labels = c("Poor (LVEF 21-30%)", "Good (LVEF >50%)", "Moderate (LVEF 31-50%)", "Very Poor (LVEF <21%)")),
    Extent_of_CorVessDx = factor(`Extent of coronary vessel disease`),
    Extracardiac_Arteriopathy = factor(`Extracardiac arteriopathy`, levels = 0:1, labels = c("No", "Yes")),
    Gender = factor(Gender),
    Hb = as.numeric(`Haemoglobin At Time Of Surgery`),
    Height = as.numeric(Height...34),
    Weight = as.numeric(Weight...69),
    BMI = as.numeric(`Body mass index`),
    BSA = as.numeric(`Body surface area`),
    PMHx_HTN = factor(`History of hypertension`),
    PMHx_NeurologicalDx = factor(`History of neurological disease`),
    PMHx_NeurologicalDysfn = factor(`History of neurological dysfunction`),
    PMHx_Mobility = factor(`History of poor mobility`),
    PMHx_PulmonaryDx = factor(`History of pulmonary disease`),
    Surgery_MI_interval = factor(`Interval between surgery and last MI`),
    IV_Inotrope = factor(`Intravenous inotropes prior to anaesthesia`),
    IV_Nitrate_Heparin = factor(`Intravenous nitrates or any heparin`),
    LeftHeart_Catheterisation = factor(`Left heart catheterisation`),
    LMS_Dx = factor(`Left main stem disease`),
    LVEF_perc = as.numeric(`Left ventricular ejection fraction`),
    Minimitral = factor(minimitral, levels = 0:1, labels = c("No", "Yes")),
    Converted = factor(case_when(`Minimal Invasive Procedure?` == "Converted" ~ 1,
                          TRUE ~ 0), levels = 0:1, labels = c("No", "Yes")),
    Num_HeartOp = as.numeric(`Number of previous heart operations`),
    Num_PrevMIs = factor(`Number of previous MIs`),
 #   OperativeFindings = as.character(`Operative Findings`),
    OperativeUrgency = factor(`Operative urgency`),
    OtherCardiacProc_Cat = factor(`Other actual cardiac procedures`),
    OtherCardiacProc_Bin = factor(`Other cardiac procedures`),
    Syst_PA = as.numeric(case_when(`PA systolic` == 0 ~ NA_real_,
                                   TRUE ~ `PA systolic`)),
    Preop_SupportDevice = factor(`Pre-op support devices used`),
    Preop_Rhythm = factor(`Pre-operative heart thythm`),
    PMHx_CardiacSurgery = factor(`Previous cardiac surgery`),
    PMHx_PCI = factor(`Previous PCI`),
    PMHx_PulHTN = factor(`Pulmonary Hypertension`),
    Pulmonary_HTN_lvl = factor(`Pulmonary Hypertension Level - If applicable`),
    Renal_Fn = factor(`Renal function / Dialysis`),
    Renal_Impairment = factor(`Renal Impairment`),
    SurgicalIncision = factor(`Surgical Incision`),
    VentilatedPreOP = factor(`Ventilated (pre-operation)`),
    Additive_EUROScore = as.numeric(`Additive EUROScore`),
    EUROScore_II = as.numeric(`EuroSCORE II`),
    Logistic_EUROScore = as.numeric(`Logistic EUROScore`),
    SCTS_Logistic_EUROScore = as.numeric(`SCTS Logistic EuroSCORE`),
    Any_Transfused = factor(`Any Transfused  Product Intra or Post Op(FFP/Plts/Red Cells)`),
 #   Arrhythmias = as.character(Arrhythmias),
    BloodLoss = as.numeric(`Blood Loss`),
    BloodTransfusedUnits = as.numeric(`Blood Transfused`),
    BloodUsed = factor(`Blood Used`),
    Cardioplegia_infusionmode = factor(`Cardioplegia - Infusion mode`),
    Cardioplegia_soluiton = factor(`Cardioplegia - solution`),
    Cardioplegia_temperature = factor(`Cardioplegia - Temperature`),
    Cardioplegia_timing = factor(`Cardioplegia - Timing`),
    Cardiopulmonary_bypass = factor(`Cardiopulmonary bypass`),
    Cause_of_Death = factor(`Cause of Death`),
    Cell_Salvage = as.numeric(`Cell Salvage`),
    CreatinineGT200 = factor(`Creatinine &gt;200, no dialysis`),
    Cryoprecipitate = as.numeric(Cryoprecipitate),
    CumulativeBypassTime = as.numeric(`Cumulative bypass time`),
    CumulativeCrossClampTime = as.numeric(`Cumulative cross clamp time`),
    Discharge_Date = as.POSIXct(`Date of discharge / Date of death in hospital...92`, format = "dd-mmm-yy", tz = "Europe/London"),
    Deep_Sternal_Inf = factor(`Deep sternal wound infection`),
    Discharge_Destination = factor(`Discharge destination from cardiothoracic ward`),
    Ventilation_Duration = factor(`Duration of Ventilation`),
    FFP = as.numeric(FFP),
    GI_Complications = factor(case_when(is.na(`GI complications`) ~ 0,
                                 TRUE ~ 1), levels = 0:1, labels = c("No", "Yes")),
    HDU_Stay = as.numeric(`HDU Stay`),
    ICU_Stay = as.numeric(`ICU Stay`),
    InotropesIntraOp = factor(`Inotropes Used`),
    IntraAorticBalloon = factor(`Intra-aortic balloon pump used`),
    MultiSystemOrganFailure = factor(`Multisystem organ failure?`),
    IntraOp_MI = factor(`Myocardial infarction`),
    IntraOp_IntrafiltrationDialysis = factor(`New haemofiltration or dialysis`),
    PostOp_NeurologicalDysfunction = factor(`New post-operative neurological dysfunction`),
    Num_AortaSegments = factor(`Number of aorta segments operated on`),
    Num_ArterialGraft = factor(`Number of arterial grafts`),
    Num_DistalCorAnas = factor(`Number of distal coronary anastamoses`),
    Num_Valves_repair_replace = factor(case_when(`Number of valves replaced/repaired` == 0 ~ 1,
                                                 TRUE ~ `Number of valves replaced/repaired`)),
    Num_VenousGrafts = factor(`Number of venous grafts`),
    DeathStatus = factor(`Patient status at discharge...123`),
    PCC = as.numeric(PCC),
    Platelets = as.numeric(Platelets),
    PostOpStay_Days = as.numeric(`Postoperative stay in days`),
    Myocardial_Protection_Method = factor(`Predominant method of myocardial protection`),
    PreOpStay_Days = as.numeric(`Preoperative stay in days`),
  #  Pulmonary_Complication = as.character(`Pulmonary complications`),
    Reason_IABP = factor(`Reason for intra-operative Intra-aortic balloon pump use`),
    RedCells_Given = as.numeric(`Red Cells Given`),
    Return_to_theatre = factor(`Return to theatre`),
    Site_Wound_Infection = factor(`Site Wound Infection`),
    TotalStay_Days = as.numeric(`Total stay in days`),
    TrasylolUsed = factor(`Trasylol used?`),
    WhyNoLima = factor(`Why Lima Not Used`),
   # GraftConduit = as.character(`Graft conduit`),
   # GraftSite = as.character(`Graft site`),
    NativeMitralPathology = factor(`native mitral valve pathology`),
    NativeTriCPathology = factor(`native tricuspid valve pathology`),
   # ProcedureSite = as.character(`Procedure site`),
    MitralValvePathology = factor(`Mitral valve haemodynamic pathology`),
    TricuspidValvePathology = factor(`Tricuspid valve haemodynamic pathology`),
    Tricuspid_Procedure_Bin = factor(tricuspid),
    Tricuspid_Procedure_RepaPepl = fct_collapse(factor(case_when(`tricuspid valve procedure` == 0 ~ NA_character_,
                                           TRUE ~ `tricuspid valve procedure`)), Repair = c("Repair with ring", "Repair without ring")),
    Tricuspid_Procedure_Full = factor(case_when(`tricuspid valve procedure` == 0 ~ NA_character_,
                                           TRUE ~ `tricuspid valve procedure`)),
    MitralValveProcedure_RepaPepl = fct_collapse(factor(`mitral valve procedure`), Repair = c("Repair with ring", "Repair without ring")),
    MitralValveProcedure_Full = factor(`mitral valve procedure`),
    MitralValveRingSize = as.numeric(`Mitral valve or ring size (mm)`),
    DateDeath = as.POSIXct(`DBS Deceased`, format = "dd/mm/yyyy", tz = "Europe/London")
    
  )

```
```{r}
theme_gtsummary_journal(journal = "jama")
#> Setting theme `JAMA`
theme_gtsummary_compact()
#> Setting theme `Compact

tbl_summary(Data, by = "MitralValveProcedure_RepaPepl") %>%
  add_p() %>%
  bold_p()
```

